### PR TITLE
Remove CUDA

### LINKED ISSUE #396: LJFunctors do not yet support SoA for VerletClusters correctly.
**Is your feature request related to a problem? Please describe.**
The LJFunctors does not yet support SoA, as the functor calls do not correctly handle the global calculations, as the owned state is not used.

**Describe the solution you'd like**
Use the owned state correctly.

**Additional context**
Once this is done:
- [ ] enable the calculation in LJFunctor::isAppropriateClusterSize(), as that function is currently disabling the SoA functionality.

### LINKED ISSUE #419: Cuda: LJFunctors throw exceptions at VERY high densities
**Describe the bug**
Both LJFunctorCuda and LJFunctorCudaGlobals throw the exception
```
C++ exception with description "Linked Cells NoN3: cuda Kernel size not available for Linked cells. Too many particles in a cell. Requested: 1024" thrown in the test body.
```
if there are too many particles in a cell. It would be nice to be able to support this, too.

**To Reproduce**
1. Remove if condition in TraversalComparison and run tests with enabled cuda.
```c++
if (dataLayoutOption == autopas::DataLayoutOption::Value::cuda and
    traversalOption == autopas::TraversalOption::Value::c01Cuda and boxMax[0] < 5. and
    numParticles > 500) {
  continue;
}
```
2. run tests

### LINKED ISSUE #498: Properly document cuda code
**Is your feature request related to a problem? Please describe.**
The cuda code is:
a) not properly documented from a Doxygen kind of perspective. To check this, please uncomment the below line in `docs/Doxyfile.in`
```
#EXTENSION_MAPPING      = h=c++ cpp=c++ cuh=c++ cu=c++
```
b) barely documented at all and hard to understand.

**Describe the solution you'd like**
Document everything properly

**Describe alternatives you've considered**
Remove cuda code, once we do not need it anymore...

**Additional context**
Detected during #491

### PR DESCRIPTION
**Pull request by FG-TUM**
# Description

Removes all Containers and traversals for CUDA. This is because they were not used, but still (sparsely) tested, which ended up being a bottleneck for Jenkins.

- [x] I suggest creating a tag `AutoPas_CUDA` before merging this into master.

Removed:
- VerletClusterCells with vcc_cluster_iteration 
- ds_sequential (CUDA version)
- lc_c01_cuda
    
## Resolved Issues

The following issues can be closed since they only refer to the here deleted code.

- closes #396
- closes #419
- closes #498 

# ~How Has This Been Tested?~

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
hmm, creating the tag is definitely useful, as it allows to test against a potential kokkos implementation.

**Comment by SteffenSeckler** [comment]
ok, created the tag: AutoPas_CUDA

**Comment by SteffenSeckler** [comment]
found some mentions of cuda in Doxyfile.in and removed it.

**Review by SteffenSeckler — APPROVED** [review]

**Comment by FG-TUM** [comment]
> hmm, creating the tag is definitely useful, as it allows to test against a potential kokkos implementation.

I actually left this in in purpose so that if there was ever any cuda code in AutoPas again Doxygen would be prepared. But I'm fine with throwing it out too.

**Pull request merged**
