### PR TITLE
Format CMakeLists.txt using cmake-format

### LINKED ISSUE #202: Prefix CMake Variables
**Is your feature request related to a problem? Please describe.**
We start to get quite a few CMake switches, some of which sound very general (ENABLE_OPENMP, ENABLE_CUDA...). Depending on how AutoPas is included in another project these variables will show up in `ccmake`. This could lead to ambiguities or even name clashes.

**Describe the solution you'd like**
Prefix all publically available Variables (=Options) with `AutoPas_`

**~Describe alternatives you've considered~**

**Additional context**
Kokkos also does this...

### LINKED ISSUE #203: CMake code convention
**Is your feature request related to a problem? Please describe.**
We mix capitalization of cmake functions pretty wildly.

**Describe the solution you'd like**
Since the doc writes functions always in lowercase I would opt for lowercase everywhere.

**Describe alternatives you've considered**
Capitalize all functions.

### PR DESCRIPTION
**Pull request by Garfield96**
# Description

All CMakeLists.txt were formatted using cmake-format. A configuration file and run script was added to perform formatting automatically.

# Todo

- [x] exclude special commands from formatting
- [x] prefix all CMake options ( #202 )

## Resolved Issues # (issue)

- [x] closes #203 
- [x] closes #202 

# How Has This Been Tested?

- [x] Jenkins

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
some notes:
- [ ] formatting should also be applied to cmake/modules/*.cmake
- [ ] formatting should be added as an additional target via a cmake module -- similar to clang-format. With that, you can remove that .sh file
- [ ] can the cmake-format.py file go somewhere else or does it have to be in the root directory of the project?
- [ ] formatting should be checked by jenkins -> needs to be add to:
  - [ ] Jenkinsfile
  - [ ] docker images (maybe simply the clang one which already includes clang-format?)

**Comment by Garfield96** [comment]
Thanks for including cmake-format into the build system.

> can the cmake-format.py file go somewhere else or does it have to be in the root directory of the project?

The path of cmake-format.py can be passed to cmake-format as an additional parameter (`--config-file`), so we can move it to any location. Which directory do you suggest?

**Comment by FG-TUM** [comment]
Check if newer Version of cmake-format fixed todos. If yes -> update

**Comment by FG-TUM** [comment]
Move cmake-format script to `AutoPas/cmake`

**Comment by Garfield96** [comment]
>     * [ ]  Check if newer Version of cmake-format fixed todos. If yes -> update

New version was released on thursday. It fixed the to-dos.

**Comment by Garfield96** [comment]
@SteffenSeckler Please install cmake-format v0.5.2 in Jenkins

**Comment by FG-TUM** [comment]
> @SteffenSeckler Please install cmake-format v0.5.2 in Jenkins

@SteffenSeckler *ping*

**Comment by SteffenSeckler** [comment]
docker build is currently running :)

**Comment by SteffenSeckler** [comment]
docker build finished successfully, please update the branch :)

**Pull request merged**
