### PR TITLE
Bugfix/yaml parser missing vtk output folder

### PR DESCRIPTION
**Pull request by TumBeat**
# Description
`YamlParser::parseYamlFile()`  was missing an if statement for the vtk-output-folder option. Because of this, one was not able to set a custom output folder via the yaml input file.

(Edit, 30.04.):
Same issue with the `CLIParser::parseInput()`.

## Resolved Issues

- [x] #740 

# How Has This Been Tested?

This fix was tested with new unit tests and by running the md-flexible program with the changed fallingDrop.yaml input file.

- [x] Specified a custom output folder and verified that the vtk-files were actually stored there
- [x] Wrote a new unit test to verify that the options in the input file end up in the configuration object
- [x] Tested the CLI-Option with calling md-flexible with "./md-flexible --yaml-filename fallingDrop.yaml  --vtk-output-folder fancyFolderName" and observed that the output files go into the correct folder

### CODE REVIEW

**Comment by FG-TUM** [comment]
From the top of my head, this also has to go into the `CLIParser::relevantOptions`. Maybe also have a look at the `CONTRIBUTING.md` file to check if I forgot something else.

**Comment by dmartin13** [comment]
It might also be a good idea to add this missing option to AllOptions.yaml.

**Comment by TumBeat** [comment]
> From the top of my head, this also has to go into the `CLIParser::relevantOptions`. Maybe also have a look at the `CONTRIBUTING.md` file to check if I forgot something else.

Seems like the CLIParser as well does not have the relevant case statement so it was not possible to specify an custom output folder at all or did I miss something?
I will add this as well in this PR and hope this is OK the main goal of this PR is about with the YamlParser.

**Comment by FG-TUM** [comment]
> so it was not possible to specify an custom output folder at all or did I miss something?

Nope, that was never a feature. 

> I will add this as well in this PR and hope this is OK the main goal of this PR is about with the YamlParser.

Awesome!

**Pull request merged**
