### PR TITLE
Test custom action

### PR DESCRIPTION
**Pull request by FG-TUM**
# THIS PR IS NOT INTENDED TO BE MERGED!

Test PR to check custom GH Action

Tests:
- [x] `ContainerIterator.h` is touched but not `Iterators.md` -> Expect warning
- [x] `Simulation.cpp` is touched and `SimulationLoop.md` -> Expect no warning
- [x] One file (`cmake-format.py`) in `cmake/` was touched but not `Building.md` -> Expect warning
- [x] No further warnings
- [x] Works also if the base branch is not `master`

### CODE REVIEW

**Comment by FG-TUM** [comment]
test comment

**Comment by FG-TUM** [comment]
test 1

**Comment by FG-TUM** [comment]
test 2

**Comment by FG-TUM** [comment]
fooooooo

**Comment by FG-TUM** [comment]
cnow<ncenv

**Comment by thesamriel** [comment]
I love this conversation

**Pull request closed without merging**
